export const NOTIFICATIONS_LOAD_START = 'NOTIFICATIONS_LOAD_START';
export const NOTIFICATIONS_LOAD_SUCCESS = 'NOTIFICATIONS_LOAD_SUCCESS';
export const NOTIFICATIONS_LOAD_ERROR = 'NOTIFICATIONS_LOAD_ERROR'
